ALTER TABLE `person` CHANGE `name` `name` VARCHAR(120) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE login ADD email VARCHAR(60) AFTER id;
ALTER TABLE `login` CHANGE `id` `id` INT(20) NOT NULL AUTO_INCREMENT;
